# Generated by Django 4.0.6 on 2022-08-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
